### ISSUE TITLE
Checking if the recovery exists always fails

### ISSUE THREAD

**Issue by Raif1** [mlm-games/TWRP_OFOX_PBRP_SHRP_Recovery_Builder#6]
![image](https://github.com/user-attachments/assets/3e9268d1-b648-4a8e-aa14-8333c92557ca)
How to fix?

**Comment by mlm-games** [comment]
I have looked into some of your action logs, and there are errors related to device tree not cloning properly, common.mk doesn't exist... So make sure it builds properly in your locally first and then try if you can't debug action logs. If it builds and then fails online, then come back here
